version: '3'

services: 
  taskadminDB:
    image: postgres:16
    container_name: 'task-admin-db'
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=juanludev
      - POSTGRES_PASSWORD=juanludev
    volumes:
      - ./postgres:/var/lib/postgresql/data